export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const ADD_SHIPPING_ADDRESS = 'ADD_SHIPPING_ADDRESS';
export const ADD_PAYEMENT_METHOD = 'ADD_PAYEMENT_METHOD';
